name: Compile Project Assets

on:
  push:
    branches: [ "*" ]

permissions:
  contents: write

jobs:
  laravel-mix-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head }}

      - name: Compile Develop Assets
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Compile Assets
        run: npm run prod

      - name: Verify widgets.js not empty
        run: |
          ls -lah public/js
          test -s public/js/widgets.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "compiled laravel mix assets"
